/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class classPackage_ClassA */

#ifndef _Included_classPackage_ClassA
#define _Included_classPackage_ClassA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     classPackage_ClassA
 * Method:    passString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_classPackage_ClassA_passString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
